name: Run Pytest

on:
  pull_request:
    branches: ["main"]

# ジョブ群
jobs:
  # ジョブ名
  test:
    runs-on: ubuntu-latest

    # 処理
    steps:
      # リポジトリのチェック
      - name: Checkout repository
        uses: actions/checkout@v4

      # Pythonの準備
      - name: Setup Python
        uses: actions/setup-python@v5
        # Pythonのバージョン指定
        with:
          python-version: 3.13

      # 必要なモジュールのインストール
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run pytest
        run: pytest

